name: Deploy to Github Pages

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 19

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [$NODE_VERSION]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: $NODE_VERSION

    - name: Install dependencies
      run: |
        npm ci

    - name: Build Angular app
      run: |
        npm run build:prod --outpu-path dis/prod

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/prod
