name: Deploy to Surge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build app
        run: npm install && npm run build -- --prod
      - name: Deploy to Surge
	env:
          SURGE_TOKEN: ${{ secrets.TOKEN_SURGE }}
        run: npx surge ./dist/konta-hery --domain konta-b.surge.sh
